### ISSUE TITLE
Missing front (a) part for the Sherpa

### ISSUE THREAD

**Issue by MaikelKelder** [Armchair-Engineering/Xol-Toolhead#14]
Cant seem to find the front part STL for the Sherpa Extruder. 
I would expect the STL in the Extruder folder, but not there, maybe I am missing it, but really tried finding it, believe me.
![image](https://github.com/Armchair-Engineering/Xol-Toolhead/assets/37801691/a010a219-4369-4e20-be9c-36d5398df9a4)

**Comment by DW-Tas** [comment]
Sherpa-Mini is maintained by Annex Engineering. We have provided links to those parts in our documentation: https://github.com/Armchair-Engineering/Xol-Toolhead/blob/main/docs/printing.md

![image](https://github.com/Armchair-Engineering/Xol-Toolhead/assets/116466447/d0ee1fdd-6c49-4643-8e5f-f648c9e9ae91)

**Comment by MaikelKelder** [comment]
Aaaah, Thank you, I looked at the default one, but noticed I needed one with a extra screw on the bottom. Thanks for the quick reply!!
