### ISSUE TITLE
Clockwork extruder support

### ISSUE THREAD

**Issue by zhou13** [Armchair-Engineering/Xol-Toolhead#15]
Hi team, does Xol support the Clockwork/Clockwork2 Extruder from Voron 2.4? It looks like it is not on the list of supported extruders.  Is there a plan to add the support for Clockwork?

**Comment by DW-Tas** [comment]
Hi. No, it isn't supported, and it won't be supported as the CW/CW2 is too big. You can use the BMG gearset out of CW2 to build a Sherpa-Mini.
