### ISSUE TITLE
Question about NF Crazy hotend mount

### ISSUE THREAD

**Issue by tjmitchem** [Armchair-Engineering/Xol-Toolhead#21]
I bought the [Magnum](https://tevoup.com/products/mellow-all-metal-nf-crazy-hotend-v6-copper-nozzle-for-ender-3-cr10-prusa-i3-mk3s-alfawise-bmg-extruder-3d-printer-parts?variant=40578823258264) version of the NF Crazy hotend.  Can I use the included mount design, or will I need something else?

**Comment by DW-Tas** [comment]
Yes, I believe that is all still the same, just with a melt zone extender built into the heat break side.

Sorry I took so long to get back to you with this.
