### ISSUE TITLE
Xol Carriage - Rear - MGN12H - 6MM.stl

### ISSUE THREAD

**Issue by YesterdaysCoffee** [Armchair-Engineering/Xol-Toolhead#25]
when oriented on the printer:
top two holes are unnecessarily deep and makes removal of screws difficult, especially when mounted on the printer with screws facing backward.  Making the counter bore shallow, instead of deep, allows fingers to grasp the screw when loose.

Also, does the hole really need to be hexagonal instead of round?

**Comment by DW-Tas** [comment]
Holes unnecessarily deep:
* The holes are that depth for the following reason
* * Standardising around M3x8 SHCS where possible to minimize BOM
* * Allowing a heatset in a small plastic insert to be placed in the hole for StealthBurner compatibility (screws inserted from front)

Hexagonal shape:
* Prevents spinning of inserted parts for StealthBurner or other mods

Removing screws:
* The intention is that screws in that location should not be removed, but stay there ready to be screwed back into the toolhead when it is re-attached.
* If you remove the toolhead, you can push the screws out from the front with the end of the hex driver.
