### ISSUE TITLE
Update probe mounts to include different beacon version mounts 

### ISSUE THREAD

**Issue by 1scottlyl** [Armchair-Engineering/Xol-Toolhead#26]
The files listed in the printing guide (https://github.com/Armchair-Engineering/Xol-Toolhead/blob/main/docs/printing.md#probe-modules) don't list the beacon rev H files, only the Rev D. 

I missed the other files for Rev H in the repo due to getting files from the print guide, and figured it could be an avoidable error in the future.

**Comment by DW-Tas** [comment]
Fixed:
![image](https://github.com/Armchair-Engineering/Xol-Toolhead/assets/116466447/15ed3388-5b58-4749-b5b1-707b8b05b5ca)
