### ISSUE TITLE
Sherpa mini with ECAS connector.

### ISSUE THREAD

**Issue by erazor666** [Armchair-Engineering/Xol-Toolhead#6]
![image](https://github.com/Armchair-Engineering/Xol-Toolhead/assets/31832864/8871634a-6ed2-4f56-9a2e-f9eb4a7f8f88)

Where can i find that Sherpa Mini part with the ECAS connector as in this picture? I cant seem to find it in the sherpa repo or in the Xol repo. If you want to run the Xol with ERCF this is a pretty vital part.

**Comment by DW-Tas** [comment]
Sherpa-mini usermod on Annex Engineering repository: https://github.com/Annex-Engineering/Annex-Engineering_User_Mods/tree/main/Extruders/Sherpa_Mini/Extruder_Mods/alch3my-Housing_Core_with_ECAS_coupler
