### ISSUE TITLE
Update DFA mounting hole pattern to use Rev4 layout

### ISSUE THREAD

**Issue by hackerjack42** [Armchair-Engineering/Xol-Toolhead#7]
The DFA mounting hole pattern was updated to a more symmetrical layout in October of 2022.  The current design appears to mesh up with the previous version of the DFA.  Is an update planned?

**Comment by DW-Tas** [comment]
Xol-Carriage replaces the bottom part for DFA that is based off rev 4 and can be found here: https://github.com/Armchair-Engineering/Xol-Toolhead/blob/main/STL/Xol-Carriage/Xol%20Carriage%20Adapters/Xol%20Adapter%20DFA.stl

**Comment by DW-Tas** [comment]
Xol-Carriage uses a custom bottom part for DFA that is based off rev 4 and can be found here: https://github.com/Armchair-Engineering/Xol-Toolhead/blob/main/STL/Xol-Carriage/Xol%20Carriage%20Adapters/Xol%20Adapter%20DFA.stl

**Comment by hackerjack42** [comment]
Perhaps I should have been more specific.  My configuration includes a Rapido and TAP.  I currently have an older version of the toolhead combined with a now deleted experimental adapter plate that managed to allow everything to bolt together.

There is no equivalent solution for this combination of parts.  The adapter plate you linked assumes that it will be paired with the Xol carriage.

https://github.com/Armchair-Engineering/Mantis-Xol/blob/main/STL/Xol%202/TAP/Rapido/Xol%202%20Rapido%20-%20Hotend%20Mount%20-%20DFA%20-%20TAP.stl

https://github.com/Armchair-Engineering/Mantis-Xol/blob/5430e57c48912b01a8f1ac0b656c8ef7206a638e/STL/Experimental/Xol%202%20-%20Adaptor%20-%20DFA%20-%20TAP.stl

**Comment by DW-Tas** [comment]
DFA is not supported with TAP on Xol-Toolhead. It put the extruder up too high and was out of balance.
![image](https://github.com/Armchair-Engineering/Xol-Toolhead/assets/116466447/ad643716-0a6e-4c03-ae0f-e115ea87bdde)

Is this the part that let your old setup work? https://github.com/Armchair-Engineering/Mantis-Xol/blob/main/STL/Modded%20Double%20Folded%20Ascender/Mantis_Xol%20-%20DFA%20Bottom.stl

**Comment by hackerjack42** [comment]
"N/A" means "Not Applicable".  If what you're saying is accurate, then it should say "Not Supported".

The deleted adapter plate I linked is what made it fit.  The two front holes were large enough for the screws to pass through from above to secure the extruder to the toolhead, and a heatset was inserted into the rear-right hole.  The adapter itself was secured to TAP with two M3 screws from the front.  This let the unmodified extruder mount using three of the four standard locations.  The orientation of the adapter plate meant that the extruder sat about 5mm higher than it normally would.  The plate mounts to TAP with the bed surface facing upwards at the extruder.  The only drawback that I could see is that cable chains would not fit and you therefore had to switch to an umbilical.

Full disclosure; I never did get the completed toolhead assembly installed on my 2.4, so I can't speak to it's balance.  I have a bunch of parts staged for installation, but haven't gotten around to doing so for various reasons.  What I can say is that the assembled toolhead _feels_ quite solid as it sits on my bench.  I agree that this isn't the most scientific bit of evidence.
