### ISSUE TITLE
Missing/wrong printing parts?

### ISSUE THREAD

**Issue by valepe** [Armchair-Engineering/Xol-Toolhead#8]
Maybe it's my fault but looking for all parts to be printed there no evidence that optional parts have to be chosen for sherpa extruder.
Under sherpa mini I had to choose:
- STLs/optional_parts/[a]_housing_front_k_x1_rev15.STL instead of STLs/[a]_housing_front_x1_rev15.STL
- STLs/optional_parts/[a]_idler_arm_short_x1_rev15.STL instead of STLs/[a]_idler_arm_long_x1_rev15.STL

I made these choices based on xol 3d model, I suggest to add a note if choosing the sherpa mini extruder

**Comment by DW-Tas** [comment]
Have added the following, including links to Annex GitHub for files.

![image](https://github.com/Armchair-Engineering/Xol-Toolhead/assets/116466447/4e1ff38b-ee5b-44a4-972a-c6e49c2a9bf6)

**Comment by patrezp** [comment]
annex just updated some STLs to rev16
<img width="1680" alt="image" src="https://github.com/Armchair-Engineering/Xol-Toolhead/assets/743265/74f2179c-df42-4db7-a2f4-bf0fe2972bae">
this is the new url for idler arm
[https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/blob/master/STLs/optional_parts/%5Ba%5D_idler_arm_short_x1_rev16.STL](https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/blob/master/STLs/optional_parts/%5Ba%5D_idler_arm_short_x1_rev16.STL
)
